[package]
  cjc-version = "1.0.0"
  name = "cjsfml"
  description = "SFML library bindings"
  version = "1.1.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = "--dy-std -O2"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  cenum = { git = "https://github.com/causerp/cenum.git", tag = "v1.1.0"}
  ctemplate = { git = "https://github.com/causerp/ctemplate.git", tag = "v1.1.0"}
  endian = { git = "https://github.com/causerp/endian.git", tag = "v1.1.0"}

[ffi.c]
  csfml-audio = { path = "./csfml" }
  csfml-graphics = { path = "./csfml" }
  csfml-network = { path = "./csfml" }
  csfml-system = { path = "./csfml" }
  csfml-window = { path = "./csfml" }
